name: Salesforce CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sfdx force:auth:sfdxurl:store -f auth.txt --setdefaultusername --setalias ciOrg
          rm -f auth.txt
          sfdx force:org:list

      - name: Run Apex tests (JUnit + coverage)
        run: |
          mkdir -p tests/apex
          sfdx force:apex:test:run -c -r junit -d ./tests/apex --codecoverage -w 20 -u ciOrg

      # ✅ Validation uniquement pour les Pull Requests
      - name: Validate deployment (checkonly on PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sfdx force:source:deploy -p force-app/main/default --checkonly -u ciOrg

      # ✅ Déploiement réel uniquement sur push -> main
      - name: Deploy to Salesforce (real deploy on push)
        if: ${{ github.event_name == 'push' }}
        run: |
          sfdx force:source:deploy -p force-app/main/default -u ciOrg

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apex-junit
          path: tests/apex
