name: Salesforce CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          # On ajoute -s pour que cette org soit la default, et alias ciOrg
          sfdx auth:sfdxurl:store -f auth.txt -s -a ciOrg
          rm -f auth.txt

      - name: Run Apex tests
        run: |
          sfdx force:apex:test:run -c -r human -w 20 --codecoverage -u ciOrg

      - name: Deploy to Salesforce (CheckOnly)
        run: |
          sfdx force:source:deploy -p force-app/main/default --checkonly -u ciOrg
