name: Salesforce CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installe le CLI Salesforce
      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      # ✅ Auth correcte (commande "force:auth:sfdxurl:store")
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sfdx force:auth:sfdxurl:store -f auth.txt --setdefaultusername --setalias ciOrg
          rm -f auth.txt
          sfdx force:org:list

      # Tests Apex + couverture (export JUnit)
      - name: Run Apex tests (JUnit + coverage)
        run: |
          mkdir -p tests/apex
          sfdx force:apex:test:run -c -r junit -d ./tests/apex --codecoverage -w 20 -u ciOrg

      # Validation de déploiement (checkonly)
      - name: Deploy to Salesforce (checkonly)
        run: |
          sfdx force:source:deploy -p force-app/main/default --checkonly -u ciOrg

      # Artefacts de test pour ton PDF
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apex-junit
          path: tests/apex
