name: Salesforce CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installe proprement le CLI Salesforce
      - name: Setup Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v2

      # Authentification via le secret GitHub: SF_AUTH_URL
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sfdx auth:sfdxurl:store -f auth.txt --setdefaultusername --setalias ciOrg
          rm -f auth.txt
          # Vérifie que l'org est bien connue (doit lister ciOrg)
          sfdx force:org:list

      # Lance les tests Apex avec couverture
      - name: Run Apex tests (JUnit + coverage)
        run: |
          mkdir -p tests/apex
          sfdx force:apex:test:run -c -r junit -d ./tests/apex --codecoverage -w 20 -u ciOrg

      # (Option validation) Déploiement en check-only
      - name: Deploy to Salesforce (checkonly)
        run: |
          sfdx force:source:deploy -p force-app/main/default --checkonly -u ciOrg

      # Conserve les rapports JUnit en artefacts (preuve pour le PDF)
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apex-junit
          path: tests/apex
